### ISSUE TITLE
Allow camelCase properties

### ISSUE THREAD

**Issue by kentcdodds** [iammerrick/CSS.js#1]
So instead of:

``` javascript
var Styles = CSS({
  'border-radius': '4px'
});
```

I can do:

``` javascript
var Styles = CSS({
  borderRadius: '4px'
});
```

**Comment by kentcdodds** [comment]
If you say you like this idea, I'd be happy to PR it for you.

**Comment by nmn** [comment]
@kentcdodds Again, since CSS.js is basically meant for react.js, this already works in React.
