### ISSUE TITLE
Convert number values to appropriate suffix

### ISSUE THREAD

**Issue by kentcdodds** [iammerrick/CSS.js#2]
So instead of:

``` javascript
var Styles = CSS({
  'border-radius': '4px'
});
```

I can do:

``` javascript
var Styles = CSS({
  'border-radius': 4
});
```

**Comment by kentcdodds** [comment]
If you say you like this idea, I'd be happy to PR it for you.

**Comment by nmn** [comment]
@kentcdodds React already does that for you so you can use number values.

**Comment by kentcdodds** [comment]
@naman34 I didn't know that! Cool! I'm also thinking of using this outside of React. I understand if @iammerrick doesn't really care to cater to that use case though.

**Comment by nmn** [comment]
The concept pretty much depends on react. How to intend to use this outside of react??

If you want something similar that is a CSS preprocessing written in js, you should look at AbsurdJS

**Comment by kentcdodds** [comment]
I heard of AbsurdJS a while ago, but never really got into it. I may investigate further. I was specifically wanting to write a library that's vanilla JavaScript and then build an abstraction on top of that for AngularJS (React likely needs no such abstraction, because it rocks). Just exploring the concept currently.
